spring:
  application:
    name: mongo-test
  data:
    mongodb:
      uri: mongodb+srv://usrnm:passwrd@clustrnm.qfnan.mongodb.net/?retryWrites=true&w=majority&appName=clustrnm
      database: Task


